# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-08 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0009_auto_20161008_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itoms_chg',
            name='area_name',
        ),
    ]
